### ISSUE TITLE
Rich notifications

### ISSUE THREAD

**Issue by Rvanlaak** [alexgibson/notify.js#24]
Rich Notifications are supported now, can the API also support those?

https://developer.chrome.com/extensions/richNotifications

**Comment by MaffooBristol** [comment]
:+1: for this.

Only available in Chrome from my limited research.

**Comment by alexgibson** [comment]
Personally I'd rather this plugin focus on the standards version, instead of anything proprietary.

**Comment by alexgibson** [comment]
I should add, there are some nice new features coming via standards!

**Comment by Rvanlaak** [comment]
:+1: for following standards. Do you have some additional info for us @alexgibson ?
