### ISSUE TITLE
Can I create notification which depends on the parameter?

### ISSUE THREAD

**Issue by salvador-dali** [alexgibson/notify.js#26]
Currently I see that I can create a static notification:

    var myNotification = new Notify('Yo dawg!', {
      body: 'This is an awesome notification'
    });

and then just invoke it with myNotification.show(). But is there a way to create a notification template and then pass parameters into it? Something like:

    var myNotification = new Notify('New messages', {
        body: 'You have ' + num + ' new messages'
    });
and then `myNotification.show({num : 4})`

**Comment by dandv** [comment]
This seems out of scope of the library. What format would be used for the placeholders? Handlebars? printf? Do we introduce a dependency on that library?

**Comment by alexgibson** [comment]
if somebody added this feature I'd like to seeing be dependency free ideally.

**Comment by brandly** [comment]
I agree with @dandv that this seems outside the scope of the library. It feels like, if you need this, you should just do something like:

```js
function showNewMessageNotification(num) {
  var myNotification = new Notify('New messages', {
    body: 'You have ' + num + ' new messages'
  });
  myNotification.show();
  return myNotification;
}
```

or you could build more structure of your own to support Handlebars or whatever templates you like.
