### ISSUE TITLE
Include examples folder showing basic usage demo

### ISSUE THREAD

**Issue by alexgibson** [alexgibson/notify.js#33]
Self-reminder that I should include an examples folder in master branch with a similar demo to: http://alxgbsn.co.uk/notify.js/

**Comment by dandv** [comment]
:+1: BTW, I've linked to your library in [the most popular answer on StackOverflow regarding browser desktop notifications](http://stackoverflow.com/questions/2271156/chrome-desktop-notification-example/13328513#13328513).

**Comment by alexgibson** [comment]
This is done in v1.2.6 https://github.com/alexgibson/notify.js/releases/tag/v1.2.6
