### ISSUE TITLE
Support `data` attribute for a Notification

### ISSUE THREAD

**Issue by johanbrook** [alexgibson/notify.js#40]
Hi! Great notification abstraction!

Just wondering, any reason for not making the `data` attribute available in the `Notify` constructor? https://developer.mozilla.org/en-US/docs/Web/API/Notification/data

*Edit:* Sorry, just saw right now that only Chrome 44 supports this. But still.

**Comment by alexgibson** [comment]
This was fixed by #60

**Comment by johanbrook** [comment]
Thanks!
