### ISSUE TITLE
update to version 1.2.6 throws error in karma/PhantomJS

### ISSUE THREAD

**Issue by ErikBean** [alexgibson/notify.js#42]
Hey guys,
I am having an issue with notify.js when running unittests out of karma/PhantomJS after updating to to notify.js v1.2.6:
`ReferenceError: Can't find variable: Notification
  at /Users/beane/Code/debug-notify.js/bower_components/notify.js/notify.js:105`

![screen shot 2015-09-25 at 3 52 38 pm](https://cloud.githubusercontent.com/assets/3444917/10113951/1a20375e-639f-11e5-9248-871b363058ea.png)

This error is thrown before any of my tests run. 
Here are my dependency versions: 
`  "devDependencies": {
    "bower": "1.5.3",
    "jasmine-core": "2.3.4",
    "karma": "0.13.10",
    "karma-jasmine": "0.3.6",
    "karma-phantomjs-launcher": "0.2.1",
    "phantomjs": "1.9.18"
  }`

Demo here: https://github.com/ErikBean/debug-notify.js

Any help with this would be great, as our dev team is stuck with the previous version until this gets resolved. 
Thanks,
-Erik

**Comment by ErikBean** [comment]
Update: I think I have a patch that will work, check out branch feature/support-PhantomJS from https://github.com/ErikBean/debug-notify.js and run npm test.
Changed line 105 of notify.js for the fix
( I can make this into a PR if you'd like )

**Comment by alexgibson** [comment]
Thanks for reporting! Sorry this is fixed in master already, I just need to push a new version which I'll do shortly.

**Comment by alexgibson** [comment]
Ok this should be fixed in [v1.2.7](https://github.com/alexgibson/notify.js/releases/tag/v1.2.7).

**Comment by alexgibson** [comment]
Ok I see the issue, thanks for reporting - reopening!

**Comment by alexgibson** [comment]
@ErikBean - can you please check [this commit](https://github.com/alexgibson/notify.js/commit/62cc926392acd8722997ef66393ac48b2915822a) it should hopefully fix the error? Thanks for your patience. Let me know and I'll create a new tag/release.

**Comment by ErikBean** [comment]
@alexgibson Yep, that seems to have resolved the error. Thank you.

**Comment by elwayman02** [comment]
@alexgibson we had another problem due to changes introduced in 1.2.6 that are now working in master. Any chance a release is forthcoming?

**Comment by alexgibson** [comment]
Yep please hold tight, thanks for your patience :+1:

**Comment by elwayman02** [comment]
:+1:

**Comment by alexgibson** [comment]
New tag release is here: https://github.com/alexgibson/notify.js/releases/tag/v1.2.8 (will be on npm shortly)
