### ISSUE TITLE
window.Notify.requestPermission throws error on IE11

### ISSUE THREAD

**Issue by ErikBean** [alexgibson/notify.js#43]
Just updated to v1.2.8. Our application does not explicitly call Notify.isSupported() to check if the browser supports web notifications, as we relied on notify.js to do this for us in the past. However, after upgrading to notify.js 1.2.8, calling Notify.requestPermission calls through to window.Notification.requestPermission() which of course throws the error "cannot read property 'requestpermission' of undefined or null."

This may or may not be an issue, depending on where the responsibility lies for determining browser support. I wanted to raise this issue because I'm not sure this was intended behavior, I didn't see anything in the release notes about the responsibility shifting to the implementer of the library. 
Any insight would be much appreciated.
Thanks,
-Erik

**Comment by alexgibson** [comment]
Yes this is intended behaviour, please see #38 for more background. It is now up to the application to check if the API is supported. Example usage is in the readme and the demo file.

**Comment by ErikBean** [comment]
Okay, thanks for the info.
