### ISSUE TITLE
isSupported() is much less usable now

### ISSUE THREAD

**Issue by kevinrenskers** [alexgibson/notify.js#44]
In my web app users have a checkbox if they want to receive desktop notifications yes or no. If their browser doesn't support notifications to begin with, I don't even want to show this checkbox. However, with the recent changes to isSupported(), I can't do this anymore because it just gives an error:

`You must only call this before calling Notification.requestPermission(), otherwise this feature detect would trigger an actual notification!`

So how am I supposed to check for support before asking my users if they want notifications?

**Comment by alexgibson** [comment]
Please see the README.md file and example for suggested usage. If you're interested in the background for this change, see #38.

**Comment by kevinrenskers** [comment]
Sorry, I did check out both the readme and the example and the problem remains the same: it is now impossible to use `Notify.isSupported()` on my settings page to see if I should present this checkbox to my users. So I was wondering if there is a solution for this?

**Comment by kevinrenskers** [comment]
Ah I see your problem.. Notification.permission can be 'granted' even when there is no browser support. Still leaves me in a pickle but yeah..

**Comment by alexgibson** [comment]
Basically, the only way to accurately feature detect Web Notifications is to now try triggering a notification itself (blame google, sigh). Obviously this can't be done if the user has already given permission, hence why the error is triggered. The suggested pattern from the Google team is to now use:

    if (!Notify.needsPermission) {
        doNotification();
    } else if (Notify.isSupported()) {
        Notify.requestPermission(onPermissionGranted, onPermissionDenied);
    }

You'll need to try and work your checkbox logic into this pattern.
