### ISSUE TITLE
After downloading the repo , it is not working on chrome .

### ISSUE THREAD

**Issue by Torakami** [alexgibson/notify.js#46]
Hi , 

below is the website on which i have found your link 
https://alxgbsn.co.uk/2013/02/20/notify-js-a-handy-wrapper-for-the-web-notifications-api/
![testedwithonlinedemo](https://cloud.githubusercontent.com/assets/16377337/11922814/af62310e-a7c0-11e5-878e-05a9518ded1b.PNG)

on the above mentioned webiste , when i tested with online demo . It works well on chrome , but then when i download the repo from github , It is not working on chrome.
clicking on notify button it should first shows allow/block notify popup and then after allowing it should start showing notifucation on chrome. Which is not happening.

Please check my attached screenshot , The popup which is coming only when you tested with online demo link , this is not coming after downloading the repo from github. And hence its not working on chrome

**Comment by alexgibson** [comment]
When testing the demo locally you need to run a web server for the API to work. See the readme for more info. Are you doing this

**Comment by Torakami** [comment]
Yo man , thanks alex.. 
I was running simple html item which I had downloaded from repo.
I didnt know that it shuould be server call.
Thanks man .. Thanks a lot.
