### ISSUE TITLE
How could add link 

### ISSUE THREAD

**Issue by cheayden** [alexgibson/notify.js#51]
Sorry I am new on front-end, I already embed as yours but I want to add link text to notify box. eg:
<a href="http://example.com">link </a>.

**Comment by alexgibson** [comment]
Sorry I don't understand the question. Can you please explain a little more clearly?

**Comment by alexgibson** [comment]
Closing this due to lack of feedback. Please re-open if you can explain your issue in some more detail.

**Comment by 2braincells2go** [comment]
I was wondering about this also. What @cheayden is asking:

How to include clickable URL link in notification?

`<a href="http://google.com">Google</a>`

or maybe

`<a href='http://google.com'>Google</a>`

**Comment by alexgibson** [comment]
You can't add HTML content to a notification. You need to handle this via the on click handler in your own JS.

**Comment by 2braincells2go** [comment]
Ok, thanks.
