### ISSUE TITLE
Different behaviour between Firefox on Debian and Windows

### ISSUE THREAD

**Issue by DjLeChuck** [alexgibson/notify.js#52]
Hi,

I have a strange behaviour with Notifications on Firefox. I use the version 45.0.1 both on Debian and Windows.

This code shows up the notification on Windows but not on Debian:

```javascript
var Notify				= require("notifyjs");
var prepareNotification	= function () {
	var timeoutNotification = new Notify("Inactivité détectée", {
		body: "Vous serez déconnecté pour cause d'inactivité dans 60 secondes.",
		closeOnClick: true,
		timeout: 5,
		icon: "http://domain.tld/example.png"
	});

	timeoutNotification.show();
};

if (!Notify.needsPermission) {
	prepareNotification();
} else if (Notify.needsPermission && Notify.isSupported()) {
	Notify.requestPermission(function () {
		prepareNotification();
	});
}
```

Your demo page works both on Windows and Debian: https://alexgibson.github.io/notify.js/

All is working fine with Chrome.

**Comment by alexgibson** [comment]
I'm afraid I don't have a Debian machine to test this on, so unless you can debug a bit more to find the issue there is not a lot more I can do (especially since the the demo example is working as expected).

It is also worth noting that the default behavior in Firefox is to automatically close notifications after 4 seconds (see #22), although you are specifying a timeout of 5 seconds here.

**Comment by alexgibson** [comment]
Also, have you checked permissions for your domain on your Debian Firefox profile? Could it be as simple as you have denied notifications?

**Comment by DjLeChuck** [comment]
Thank you for your fast reply. :smile: 

After some tests the problem comes from `icon` option. If I comment the line the Notification shows up; The `timeout` works like a charm.

I continue my investigation!

**Comment by alexgibson** [comment]
Your code example above does not contain an icon, just fyi.

**Comment by DjLeChuck** [comment]
That's what I saw... Sorry bad example, I just edit my issue.

**Comment by alexgibson** [comment]
So it sounds like the issue is with your icon, not notify.js?

**Comment by alexgibson** [comment]
Sounds like this is the issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1233086

**Comment by DjLeChuck** [comment]
Yes, it's definitely not links with your library, sorry. :)

**Comment by alexgibson** [comment]
No problem! Glad you managed to debug what was causing the issue
