### ISSUE TITLE
How to push notification via form

### ISSUE THREAD

**Issue by johanvena** [alexgibson/notify.js#54]
I want to push notification via input form for Title, Description and link ( Icon will always be static) - I post and retrieve data from/to xml file

`<form method="POST"><font color="red"> Title <br><input type="text-name" value="<?php echo $title->nodeValue  ?>" style="width:250px; height:30px;" maxlength="76" name="titlenya"/><br>
  			Description <br><input type="text-name" value="<?php echo $description->nodeValue  ?>"  style="width:250px; height:30px;" maxlength="150" name="descriptionnya"/></font><br>
  			
  <input name="submit9" type="submit" value="Submit" />
  </form>      `

The icon I want to use profile pic and upload it via a script file to set and adjust image so will always be showing profile pic

Then I just want to include a url to click to.

Can you assist or advice me

Thanx
Johan

**Comment by alexgibson** [comment]
Sorry, I just don't have time to help you write your application. If you have a specific question about using this library then I am happy to help.

**Comment by johanvena** [comment]
Thanxs, do understand will code myself just need to know how do you push new messages I don’t fully understand your readme document

**Comment by alexgibson** [comment]
Can you explain what you don't understand in the readme?

Also please be aware this lib is for web notifications. Push notifications use a different API and require a Service Worker.

**Comment by johanvena** [comment]
Ok so to do push notifications you need an api that requires a Service Worker. So This lib can’t do push notifications. Any reference to a simple push notification api

**Comment by alexgibson** [comment]
Try MDN: https://developer.mozilla.org/
