### ISSUE TITLE
Npm install does not install the newest notify.js version (version bump needed)

### ISSUE THREAD

**Issue by Nederby** [alexgibson/notify.js#55]
On ```npm install notifyjs``` npm will install notifijs 1.2.8 from 2015-10-01 

The version of notify.js that gets install seems to be https://github.com/alexgibson/notify.js/blob/62cc926392acd8722997ef66393ac48b2915822a/notify.js

Without the "requireInteraction", "closeOnClick" and "silent" options.

Does the repo need a version bump to 1.2.9 ?

**Comment by alexgibson** [comment]
I'll do a release soon when ready, thanks for your patience.

**Comment by alexgibson** [comment]
v1.3.0: https://github.com/alexgibson/notify.js/releases/tag/v1.3.0
