### ISSUE TITLE
jspm not found

### ISSUE THREAD

**Issue by julien-f** [alexgibson/notify.js#64]
I think it's unreasonable for a package to require the user to manually install something to be able to use your package.

Your package may depend on jspm if you want but I expect all package to be installable simply with a `npm install`.

For instance, all my packages (see [this one](https://github.com/julien-f/js-json-rpc-protocol) for instance) are transpiled to ES5 before publishing.

**Comment by alexgibson** [comment]
I'm working to fix this now, thanks

**Comment by perrin4869** [comment]
@julien-f sorry, that was my fault, not sure why I added the `postinstall` script to `package.json`...

**Comment by julien-f** [comment]
Thanks :)

**Comment by alexgibson** [comment]
Hmm, so right now I'm having trouble with Travis not running `jspm install` since `postinstall` was removed. Once I figure what I'm not doing right to fix this, I can do another minor version bump.

**Comment by perrin4869** [comment]
maybe change `prepublish` to `jspm install && npm run build`?

**Comment by alexgibson** [comment]
> maybe change prepublish to jspm install && npm run build?

Would this not result in the same issue? From what I can tell, `prepublish` is run as part of `install` by default

**Comment by julien-f** [comment]
`jspm` should probably be a dev dependency and run automatically via `prepublish`.

**Comment by alexgibson** [comment]
`jspm` is already a dev dependency, but it needs to install some dependencies itself

**Comment by julien-f** [comment]
@alexgibson `prepublish` is run before publishing the package, therefore only the compiled version will be shipped.

**Comment by alexgibson** [comment]
From what I can see, `prepublish` seems to be run as part of npm install too?

**Comment by julien-f** [comment]
Yes, but only in development, not when installed as a dependency.

**Comment by alexgibson** [comment]
Ah I see, ok thanks. I will try @perrin4869 suggestion - thanks

**Comment by alexgibson** [comment]
Ok, that seemed to work - will bump to v2.0.2

**Comment by alexgibson** [comment]
Ok, this should now be fixed in 2.0.1 - thanks for patience and tips 🐝

**Comment by julien-f** [comment]
Thank you :)
