### ISSUE TITLE
Showing comprehensive notification like gmail etc

### ISSUE THREAD

**Issue by anup4ranium** [alexgibson/notify.js#65]
Hi @alexgibson  , Can we show comprehensive notification including logo , large text etc. like gmail does ?
Currently only limited text is showing .

**Comment by alexgibson** [comment]
This library is a simple wrapper for the Web Notification API. To see what's supported by that API, take a look at the W3C specification:

http://www.w3.org/TR/notifications/

Or MDN:

https://developer.mozilla.org/en-US/docs/Web/API/notification
