### ISSUE TITLE
Can't install latest version with Bower

### ISSUE THREAD

**Issue by adambiggs** [alexgibson/notify.js#67]
I just tried to upgrade from v1.3.0 to the latest v2.0.2. But after running `$ bower install`, the installation directory no longer contains a `notify.js` file (or any other `.js`).

**Comment by alexgibson** [comment]
I'm afraid I'm no longer supporting Bower as of the latest version. You'll have to use npm, or alternatively build from source and includ it in your project.

**Comment by alexgibson** [comment]
I guess I could still include the ES6 source code for bower installs, but you would still need to do the build step manually. I'll see if I can fix this at least, but I'd still suggest moving to npm.

**Comment by adambiggs** [comment]
Unfortunately moving to NPM or adding a build step isn't an option for our codebase. Any reason why you don't include `dist` assets in this repo?

**Comment by alexgibson** [comment]
Hmm, I was trying to avoid committing the built dist to the repo. However if you really can't move to npm then maybe I should reconsider. I'll look into it, thanks for your patience.

**Comment by adambiggs** [comment]
No problem! I know it's not ideal to commit build assets... But unfortunately it's the only way for a JS library to be usable in every environment.

I've found it helpful to set up a release task like `$ npm run release` that compiles `dist` assets, and then commits/tags the result.

That way you don't need to deal with `dist` changes for every commit, and contributors don't need to worry about it at all. Plus you can do other useful stuff with this like bump the semver version, generate a changelog, etc.

Maybe you know all this already though 😄

**Comment by alexgibson** [comment]
OK, the `dist` directory is now included in the repo, and I just tagged `v2.0.3`. This should hopefully work for you now.

**Comment by adambiggs** [comment]
Thanks!
