### ISSUE TITLE
Add url parameter

### ISSUE THREAD

**Issue by grundic** [alexgibson/notify.js#69]
Would it be possible to add `url` parameter, which should be opened whenever someone clicks the notification?
Right now it could be done via `notifyClick ` event, but parameter should make it a little bit easier.

**Comment by alexgibson** [comment]
The Notification `data` attribute might be of use to you here https://developer.mozilla.org/en-US/docs/Web/API/notification/data

**Comment by grundic** [comment]
Thank you for clarification.
What I mean was to add special attribute to skip `notifyClick` handling. But nevermind, I already overcome it.
