### ISSUE TITLE
Help Needed !

### ISSUE THREAD

**Issue by leovarmak** [alexgibson/notify.js#70]
Hey !
I want a notification to popup on a particular day. As I will pack this into an app with electron and it will keep running in the background. Now I need a bit of assistance. The notification doesn't come until I reload the page. So If someone can help me with service worker kind of thing I will be really glad( I'm a noob). Please help me out.

This is the code so far
https://gist.github.com/leovarmak/f98a0ea24cb210c8189e86decffa06b5

**Comment by alexgibson** [comment]
This library is for the Web Notification API. To use service workers you'all need to use Push Notifications, which is a different API and something library does not yet support.

You can read more about Service workers here: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers

**Comment by alexgibson** [comment]
Of course , it may be a case that you do not need push notifications to do what you need. You may just need to write some code that periodically polls every so often and checks the date.

I'm afraid I don't have time to help with support requests that go beyond the scope of the library itself, but with a bit of research and googling you can probably figure this out.
