### ISSUE TITLE
expose Notify for CommonJS 

### ISSUE THREAD

**Issue by mavrick** [alexgibson/notify.js#74]
I'm building with Grunt and not using ES6 includes with babel or webpack. 

Would be handy for the lib to attach to window.Notify if possible

Cheers

**Comment by alexgibson** [comment]
The library uses UMD, so a global should not be a problem. This is how the example demonalready works.

**Comment by mavrick** [comment]
![image](https://cloud.githubusercontent.com/assets/357659/23698856/dd5e02d8-0438-11e7-860b-ec559124b460.png)
Hmmm, I must be missing something. 

I took a look at the demo code and it couldn't be more simple 😄

**Comment by alexgibson** [comment]
I'm really not sure what you're doing here, can you give some more info?

**Comment by mavrick** [comment]
So, I have two files. ``base.js`` and ``app.js``. ``base.js`` contains all my libs like notify.js and then ``app.js`` contains the angular app. 

All I'm trying to do is call upon Notify - nothing outlandish ;) But yea, I must have a conflict somewhere. 

Will dig deeper. Looking forward to getting this working! 👊

**Comment by mavrick** [comment]
![image](https://cloud.githubusercontent.com/assets/357659/23699322/662e1a48-043a-11e7-971e-eafc4b1f9ebd.png)
That looks better, apologies for not checking more before opening a ticket. Just needed to walk away for a minute

**Comment by alexgibson** [comment]
No worries, glad it's working for you 👍
