### ISSUE TITLE
No /dist/notify.min.js ?

### ISSUE THREAD

**Issue by Shuunen** [alexgibson/notify.js#78]
Hi !

First thanks for your lib :+1: 

Is having a minified version planned ?

**Comment by alexgibson** [comment]
Not really, minifying is something that is better handled during your own build/deployment process imo.

**Comment by Shuunen** [comment]
Sure minify is part of build, I was looking for the minified file in your repo to compare the size when minified to other notification library :)

**Comment by alexgibson** [comment]
The library is 6.3kb when uncompressed. Even before minifying it's a sure sign that it's going to be pretty tiny ;)

**Comment by Shuunen** [comment]
yes right, even un-minified your lib is half the size of the others i've seen so far
