### ISSUE TITLE
You may need to request permission.

### ISSUE THREAD

**Issue by ran-j** [alexgibson/notify.js#85]
I got this error :
```
Permission has been granted by the user
index.html:42 Error showing notification. You may need to request permission.
```

```
O Google Chrome está atualizado
Versão 67.0.3396.99 (Versão oficial) 64 bits
```

**Comment by alexgibson** [comment]
It's very unlikely that I can help you without any code example to reproduce this error.

The demo page works for me in Chrome 67: https://alexgibson.github.io/notify.js/

**Comment by ran-j** [comment]
I finded the error, I can't just open the index.html on my browser I need to raise a server to work with notify.

**Comment by alexgibson** [comment]
> I finded the error, I can't just open the index.html on my browser I need to raise a server to work with notify.

You need to run a server locally to create Notifications in the browser. This is by design.
